%% Import data from spreadsheet MetaDataFile.xlsx\Constrains
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\amitk\OneDrive - Systematics LTD\Desktop\Amit\Consults\Strauss - oats\StraussDeployment\MetaDataFile.xlsx
%    Worksheet: Constrains
%
% Auto-generated by MATLAB on 11-Aug-2021 11:47:56

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 12);

% Specify sheet and range
opts.Sheet = "Constrains";


% Specify column names and types
opts.VariableNames = ["SerialNumber", "Recipe", "LifeTime", "P_300", "P_400", "P_450", "P_500", "P_600", "P_700", "P_800", "P_900", "P_1200"];
opts.VariableTypes = ["double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Recipe", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Recipe", "EmptyFieldRule", "auto");

% Import the data
MetaDataFile_Constarains = readtable("C:\Users\amitk\OneDrive - Systematics LTD\Desktop\Amit\Consults\Strauss - oats\StraussDeployment\MetaDataFile.xlsx", opts, "UseExcel", false);

MetaDataFile_Constarains = MetaDataFile_Constarains(~isnan(MetaDataFile_Constarains.SerialNumber),:);

%% Clear temporary variables
clear opts