%% Import data from spreadsheet MetaDataFile.xlsx\Times
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\amitk\OneDrive - Systematics LTD\Desktop\Amit\Consults\Strauss - oats\StraussDeployment\MetaDataFile.xlsx
%    Worksheet: Times
%
% Auto-generated by MATLAB on 11-Aug-2021 11:10:42

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = "Times";

% Specify column names and types
opts.VariableNames = ["SerialNumber", "Recipe", "CookingTime", "CleaningTime", "Group"];
opts.VariableTypes = ["double", "string", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Recipe", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Recipe", "EmptyFieldRule", "auto");

% Import the data
MetaDataFile_Times = readtable("C:\Users\amitk\OneDrive - Systematics LTD\Desktop\Amit\Consults\Strauss - oats\StraussDeployment\MetaDataFile.xlsx", opts, "UseExcel", false);

MetaDataFile_Times = MetaDataFile_Times(~isnan(MetaDataFile_Times.SerialNumber),:);

%% Clear temporary variables
clear opts